#!/usr/bin/env bash

set -euo pipefail

cd "$(dirname "$0")"
cmd="${1:-}"

case "$cmd" in
    build)
        echo "Configuring and building qi for Debian host install"
        set -x
        cd qi
        ./Configure centos7
        make
        ;;
    initdb-books)
        echo "Initializing books profile under /opt/nameserv/db"
        set -x
        /opt/nameserv/util/db/initdb-books
        ;;
    ph)
        echo "Launching ph client in interactive mode"
        echo "Don't forget to specify the server host with '-s hostname'"
        set -x
        /opt/nameserv/bin/ph "${@:2}"
        ;;
    qi)
        echo "Connecting to qi server in local admin mode"
        set -x
        /opt/nameserv/bin/qi "${@:2}"
    ;;
    daemon)
        /opt/nameserv/bin/qi -d -q
        ;;
    install)
        echo "Installing qi/ph binaries and docs into /opt/nameserv"
        set -x
        cd qi
        sudo make install
        sudo cp -r help /opt/nameserv/help
        sudo install -m 0644 doc/ph.1 /usr/share/man/man1/ph.1
        sudo install -m 0644 doc/qi.8 /usr/share/man/man8/qi.8
        sudo mkdir -p /opt/nameserv/util/db
        sudo install -m 0644 ../util/db/books.cnf /opt/nameserv/util/db/books.cnf
        sudo install -m 0644 ../util/db/books.input /opt/nameserv/util/db/books.input
        sudo install -m 0755 ../util/db/initdb-books /opt/nameserv/util/db/initdb-books
        ;;
    install-primes)
        echo "Building/installing legacy 'primes' helper used by sizedb"
        set -x
        cd util/primes
        make primes
        sudo make install
        ;;
    *)
        echo "Unrecognized command, must be one of the following:"
        echo "  build            : Configure and compile qi locally"
        echo "  install          : Install qi/ph under /opt/nameserv"
        echo "  install-primes   : Build/install util/primes helper"
        echo "  initdb-books     : Initialize the book-review db"
        echo "  ph               : Launch the ph client"
        echo "  qi               : Launch the qi server in local hero mode"
        echo "  daemon           : Launch the qi server in inetd daemon mode"
        exit 1
        ;;
esac
